### ISSUE TITLE
Scroll en chat: improvements

### ISSUE THREAD

**Issue by heyimjuani** [jsilveira/warro-dance-party#16]
Me imagino que el comportamiento ideal sería mas o menos asi:
- si estoy escroleado hasta el ultimo mensaje (o sea, el bottom), los nuevos mensajes van a hacer que el scroll siga en el bottom. Ahora mismo, estando en el bottom, si entra un nuevo mensaje para verlo hay que scrollear. Creo que hay un bugcito que no está teniendo en cuenta cierto offset para scrollear hasta el bottom con un nuevo mensaje.
- si estaba scrolleado hacia más arriba, los nuevos mensajes no deberían forzar el scroll hasta el bottom. Podríamos considerar mostrar un botoncito o algún tipo de indicador que avise que hay nuevos mensajes.

**Comment by jsilveira** [comment]
El primer item está arreglado. 

Todavía pasa lo que pusiste en el segundo item, te scrollea siempre sin importar si vos estabas a manopla scrolleando para arriba

**Comment by jsilveira** [comment]
Fixed in 9fee4a4475ea407b33e40f757bb209a026bf8530
