### ISSUE TITLE
[UX] No bloquear la UI para pedir nombre de usuario

### ISSUE THREAD

**Issue by mrezk** [jsilveira/warro-dance-party#6]
Hay varias formas de resolver esto, para salir del apuro pondría el dialog sobre el chat.

**Comment by heyimjuani** [comment]
Asi es como lo habia armado yo. Paso screens.

![image](https://user-images.githubusercontent.com/467712/78613071-3d9b0b80-7841-11ea-8473-7c4214403a10.png)
Al escribir aparece el call to action.

![image](https://user-images.githubusercontent.com/467712/78613118-5a374380-7841-11ea-917d-b9882143ec59.png)
Cuando se envía el nombre aparece el campo de comments normal.

![image](https://user-images.githubusercontent.com/467712/78613159-789d3f00-7841-11ea-99a4-c6288070e69b.png)


Todo esto está en mi zip, el que subi a dropbox, disponible aca: https://www.dropbox.com/s/09w0z8dteaee0ck/radio%203-4%2020-19.zip?dl=0

El html se ve asi, en el index.html, linea 242. Lo que _importa_ es la "enter-name"

```
<div class="send-msg-bar">
        <div id="send-message">
          <input type="text" class="form-control" value="" placeholder="Ingresa un mensaje…">
          <button class="btn btn-primary btn-send ml-2"><i aria-hidden="true" class="material-icons">chevron_right</i></button>
          <button class="btn btn-primary btn-react ml-2">🤜</button>
        </div>
        <div id="enter-name">
          <input type="text" class="form-control" value="" placeholder="Decinos quien sos para poder chatear">
          <button class="btn btn-primary btn-send ml-2"><i aria-hidden="true" class="material-icons">chevron_right</i></button>
        </div>
      </div>
```

En el css esta todo lo necesario para que los comportamientos de ambos inputs sean los esperados.

**Comment by jsilveira** [comment]
Esto está parcialmente solucionado en el último commit. No implementé la versión sofisticada de @heyimjuani pero aunque sea ya no se bloquea el play ni la UI principal.
