### ISSUE TITLE
[UX] Sacar la animación del chat cuando hablás, pero...

### ISSUE THREAD

**Issue by mrezk** [jsilveira/warro-dance-party#9]
Si escribiste texto, que te muestre el emoji  💬en el circulito del user
Si escribiste un emoji, que muestre ese emoji en el circulito del user

Podemos hacer que dure 30 segundos y quizás que pueda mostrar hasta 5 emojis

**Comment by jsilveira** [comment]
Yo dejaría la animación pero haría que arranque en el circulo del user y que capaz no sea tan grande. y que sea proporcional al largo del texto. Si es largo, crece poco (y lo capeamos además). Si es corto "largalooo" que siga siendo como ahora. Qué opinás?

**Comment by mrezk** [comment]
Me kb

**Comment by jsilveira** [comment]
Por ahora ya dejé de mostrarlo para comments de más de 20 caracteres, y achiqué un poco el globo. Falta hacer que salgan del user que los dijo

**Comment by jsilveira** [comment]
Implementado bien en 3b1235d933ea5e7a4aae36d970b2bb8da773b30d
